before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-master:
  only:
    - master
  stage: build
  script:
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f Dockerfile --push .

build-tag:
  only:
    - tags
  stage: build
  script:
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f Dockerfile --push .

build-testing:
  only:
    - web
  stage: build
  script:
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $CI_REGISTRY_IMAGE:testing-$CI_COMMIT_SHA -f Dockerfile --push .
