before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-master:
  only:
    - master
  stage: build
  script:
    - docker buildx build --platform linux/arm -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f Dockerfile.armhf .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:armhf
    - docker push $CI_REGISTRY_IMAGE:armhf
    - docker rmi $CI_REGISTRY_IMAGE:armhf
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build-tag:
  only:
    - tags
  stage: build
  script:
    - docker buildx build --platform linux/arm -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f Dockerfile.armhf .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}-armhf
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}-armhf
    - docker rmi $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}-armhf
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    
build-testing:
  only:
    - web
  stage: build
  script:
    - docker buildx build --platform linux/arm -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f Dockerfile.armhf .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:testing-armhf
    - docker push $CI_REGISTRY_IMAGE:testing-armhf
    - docker rmi $CI_REGISTRY_IMAGE:testing-armhf
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
