name: Docker CI Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin      
      - 
        name: Build and push Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t nico640/s6-debian-node:latest -f Dockerfile --push .
