name: Docker CI Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get tag
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      -
        name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin      
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - 
        name: Build and push Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t nico640/s6-debian-node:$RELEASE_VERSION -f Dockerfile --push .
